name: bond_network
description: Network is a Bond package provides a convenient way to handle API response.
version: 0.0.1+1
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: any
  equatable: any
  json_annotation: any
  json_serializable: any
  meta: any
  shared_preferences: any
  package_info_plus: any
  faker: any

  bond_core: ^0.0.1+1
  bond_cache: ^0.0.1+1