name: bond_form
description: Form is a Bond package provides a convenient way to handle Form.
version: 0.0.1
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any
  riverpod: any
  intl: any

  bond_core: ^0.0.1