name: bond_core
description: Bond Core Foundational Library for the Flutter Bond framework.
version: 0.0.1+1
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: any
  get_it: any

